<h1>Импорт библиотек

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [ ]:
import numpy as np

def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    if len(X) != len(V):
        raise ValueError("Length of matrices and vectors must be the same.")
    total_sum = np.zeros_like(V[0])  # Инициализируем сумму с нулевым вектором того же размера
    for x, v in zip(X, V):
        total_sum += np.dot(x, v)  # Умножаем матрицу на вектор и добавляем к общей сумме return total_sum

# Тесты
import unittest

class TestSumProd(unittest.TestCase):
    def test_basic_case(self):
        X = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])]
        V = [np.array([[1], [1]]), np.array([[1], [1]])]
        result = sum_prod(X, V)
        expected = np.array([[30], [70]])  # (1+2)+(5+6), (3+4)+(7+8)
        np.testing.assert_array_equal(result, expected)

    def test_different_sizes(self):
        X = [np.array([[1, 2]]), np.array([[3, 4]])]
        V = [np.array([[1]]), np.array([[1]])]
        result = sum_prod(X, V)
        expected = np.array([[4]])  # 1*1 + 2*1 + 3*1 + 4*1
        np.testing.assert_array_equal(result, expected)

    def test_error_on_different_lengths(self):
        X = [np.array([[1, 2]])]
        V = [np.array([[1]]), np.array([[1]])]
        with self.assertRaises(ValueError):
            sum_prod(X, V)

if __name__ == '__main__':
    unittest.main()

<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [ ]:
import numpy as np

def binarize(M, threshold=0.5):
    '''
    Бинаризует матрицу M по заданному порогу threshold.
    Все значения больше threshold становятся равными 1, остальные — 0.
    '''
    return (M > threshold).astype(int)  # Преобразуем булев массив в целочисленный

# Тесты
import unittest

class TestBinarize(unittest.TestCase):
    def test_basic_case(self):
        M = np.array([[0.1, 0.6], [0.4, 0.8]])
        result = binarize(M, threshold=0.5)
        expected = np.array([[0, 1], [0, 1]])
        np.testing.assert_array_equal(result, expected)

    def test_all_below_threshold(self):
        M = np.array([[0.1, 0.2], [0.3, 0.4]])
        result = binarize(M, threshold=0.5)
        expected = np.array([[0, 0], [0, 0]])
        np.testing.assert_array_equal(result, expected)

    def test_all_above_threshold(self):
        M = np.array([[0.6, 0.7], [0.8, 0.9]])
        result = binarize(M, threshold=0.5)
        expected = np.array([[1, 1], [1, 1]])
        np.testing.assert_array_equal(result, expected)

    def test_edge_case_threshold(self):
        M = np.array([[0.5, 0.5], [0.5, 0.5]])
        result = binarize(M, threshold=0.5)
        expected = np.array([[0, 0], [0, 0]])  # В данном случае, значения равные threshold становятся 0
        np.testing.assert_array_equal(result, expected)

if __name__ == '__main__':
    unittest.main()

<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
import numpy as np

def unique_rows(mat):
    #Возвращает уникальные элементы из каждой строки матрицы.
    return [np.unique(row) for row in mat]

def unique_columns(mat):
    #Возвращает уникальные элементы из каждой колонки матрицы.
    return [np.unique(col) for col in mat.T]  # Транспонируем матрицу для обработки колонок

# Тесты
import unittest

class TestUniqueElements(unittest.TestCase):
    def test_unique_rows(self):
        mat = np.array([[1, 2, 2], [3, 4, 4], [5, 5, 5]])
        result = unique_rows(mat)
        expected = [np.array([1, 2]), np.array([3, 4]), np.array([5])]
        for r, e in zip(result, expected):
            np.testing.assert_array_equal(r, e)

    def test_unique_columns(self):
        mat = np.array([[1, 2, 2], [3, 4, 4], [1, 4, 5]])
        result = unique_columns(mat)
        expected = [np.array([1, 3]), np.array([2, 4]), np.array([2, 4, 5])]
        for r, e in zip(result, expected):
            np.testing.assert_array_equal(r, e)

    def test_empty_matrix(self):
        mat = np.array([[]])
        result_rows = unique_rows(mat)
        result_columns = unique_columns(mat)
        self.assertEqual(result_rows, [[]])
        self.assertEqual(result_columns, [[]])

if __name__ == '__main__':
    unittest.main()

<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
mport numpy as np
import matplotlib.pyplot as plt

def generate_random_matrix(rows, cols):
    '''
    Генерирует матрицу случайных чисел, распределенных по нормальному закону.
    '''
    return np.random.normal(loc=0, scale=1, size=(rows, cols)

def calculate_statistics(mat):
    '''
    Рассчитывает математическое ожидание и дисперсию для каждой строки и столбца.
    '''
    row_means = np.mean(mat, axis=1)
    row_vars = np.var(mat, axis=1)
    col_means = np.mean(mat, axis=0)
    col_vars = np.var(mat, axis=0)
    
    return {
        'row_means': row_means,
        'row_vars': row_vars,
        'col_means': col_means,
        'col_vars': col_vars }

def plot_histograms(mat):
    '''
    Строит гистограммы значений для каждой строки и столбца матрицы.
    '''
    # Гистограммы для строк
    for i in range(mat.shape[0]):
        plt.figure()
        plt.hist(mat[i], bins=10, alpha=0.7)
        plt.title(f'Histogram of Row {i}')
        plt.xlabel('Value')
        plt.ylabel('Frequency')
        plt.grid()
        plt.show()

    # Гистограммы для столбцов
    for j in range(mat.shape[1]):
        plt.figure()
        plt.hist(mat[:, j], bins=10, alpha=0.7)
        plt.title(f'Histogram of Column {j}')
        plt.xlabel('Value')
        plt.ylabel('Frequency')
        plt.grid()
        plt.show()

# Пример использования
if __name__ == '__main__':
    rows, cols = 5, 3  # Задаем размеры матрицы random_matrix = generate_random_matrix(rows, cols)
    statistics = calculate_statistics(random_matrix)
    print(statistics)
    plot_histograms(random_matrix)

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
import numpy as np
import unittest

def generate_chessboard_matrix(m, n, a, b):
    '''
    Генерирует матрицу (m, n) в шахматном порядке, заполняя ее числами a и b.
    '''
    matrix = np.zeros((m, n), dtype=int)
    for i in range(m):
        for j in range(n):
            if (i + j) % 2 == 0:
                matrix[i, j] = a
            else:
                matrix[i, j] = b
    return matrix

class TestChessboardMatrix(unittest.TestCase):
    def test_chessboard_matrix(self):
        # Тест 1
        result = generate_chessboard_matrix(2, 2, 1, 0)
        expected = np.array([[1, 0], [0, 1]])
        np.testing.assert_array_equal(result, expected)

        # Тест 2
        result = generate_chessboard_matrix(3, 3, 2, 3)
        expected = np.array([[2, 3, 2], [3, 2, 3], [2, 3, 2]])
        np.testing.assert_array_equal(result, expected)

        # Тест 3
        result = generate_chessboard_matrix(4, 5, 5, 10)
        expected = np.array([[5, 10, 5, 10, 5], [10, 5, 10, 5, 10], 
                             [5, 10, 5, 10, 5], [10, 5, 10, 5, 10]])
        np.testing.assert_array_equal(result, expected)

if __name__ == '__main__':
    unittest.main()

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import unittest

def draw_rectangle(m, n, a, b, bg_color, rect_color):
    '''
    Рисует прямоугольник на изображении заданного размера.
    '''
    image = np.zeros((m, n, 3), dtype=np.uint8)
    image[:] = bg_color  # Задаем цвет фона # Рисуем прямоугольник
    image[a:a + b, :n] = rect_color  # Прямоугольник на всем протяжении по ширине
    return image

def draw_oval(m, n, a, b, bg_color, oval_color):
    '''
    Рисует овал на изображении заданного размера.
    '''
    image = np.zeros((m, n, 3), dtype=np.uint8)
    image[:] = bg_color  # Задаем цвет фона

    y, x = np.ogrid[:m, :n]
    mask = ((x - n // 2) ** 2) / (a ** 2) + ((y - m // 2) ** 2) / (b ** 2) <= 1
    image[mask] = oval_color  # Задаем цвет овала
    return image

class TestDrawingFunctions(unittest.TestCase):
    def test_draw_rectangle(self):
        bg_color = [255, 255, 255]  # Белый фон rect_color = [255, 0, 0]     # Красный прямоугольник image = draw_rectangle(10, 10, 2, 5, bg_color, rect_color)
 # Проверяем, что прямоугольник нарисован self.assertTrue(np.array_equal(image[2:7, :10], rect_color))

    def test_draw_oval(self):
        bg_color = [255, 255, 255]  # Белый фон oval_color = [0, 255, 0]     # Зеленый овал
        image = draw_oval(10, 10, 3, 2, bg_color, oval_color)
        
        # Проверяем, что овал нарисован
        center = (5, 5)
        for i in range(10):
            for j in range(10):
                if ((j - center[1]) ** 2) / (3 ** 2) + ((i - center[0]) ** 2) / (2 ** 2) <= 1:
                    self.assertTrue(np.array_equal(image[i, j], oval_color))

if __name__ == '__main__':
    unittest.main()

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [10]:
import numpy as np

def calculate_statistics(time_series):
    '''
    Вычисляет математическое ожидание, дисперсию и СКО временного ряда.
    '''
    mean = np.mean(time_series)
    variance = np.var(time_series)
    std_dev = np.std(time_series)
    return mean, variance, std_dev

def find_local_extrema(time_series):
    '''
    Находит локальные максимумы и минимумы в временном ряде.
    '''
    local_maxima = []
    local_minima = []
    
    for i in range(1, len(time_series) - 1):
        if time_series[i] > time_series[i - 1] and time_series[i] > time_series[i + 1]:
            local_maxima.append(time_series[i])
        elif time_series[i] < time_series[i - 1] and time_series[i] < time_series[i + 1]:
            local_minima.append(time_series[i])
    
    return local_maxima, local_minima

def moving_average(time_series, p):
    '''
    Вычисляет скользящее среднее временного ряда с размером окна p.
    '''
    return np.convolve(time_series, np.ones(p)/p, mode='valid')

# Пример использования
time_series = [1, 3, 2, 5, 4, 6, 5, 7, 8, 7, 6, 5, 4]
mean, variance, std_dev = calculate_statistics(time_series)
local_maxima, local_minima = find_local_extrema(time_series)
moving_avg = moving_average(time_series, 3)

print("Математическое ожидание:", mean)
print("Дисперсия:", variance)
print("Стандартное отклонение:", std_dev)
print("Локальные максимумы:", local_maxima)
print("Локальные минимумы:", local_minima)
print("Скользящее среднее:", moving_avg)

Математическое ожидание: 4.846153846153846
Дисперсия: 3.8224852071005917
Стандартное отклонение: 1.9551176964828976
Локальные максимумы: [3, 5, 6, 8]
Локальные минимумы: [2, 4, 5]
Скользящее среднее: [2.         3.33333333 3.66666667 5.         5.         6.
 6.66666667 7.33333333 7.         6.         5.        ]


<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [11]:
import numpy as np

def one_hot_encoding(class_vector):
    '''
    Выполняет one-hot-encoding для данного вектора меток классов.
    '''
    unique_classes = np.unique(class_vector)
    one_hot_matrix = np.zeros((len(class_vector), len(unique_classes)), dtype=int)
    for i, label in enumerate(class_vector):
        one_hot_matrix[i, label] = 1 
        return one_hot_matrix

# Пример
class_vector = [0, 2, 3, 0]
one_hot_result = one_hot_encoding(class_vector)

print("One-hot encoding:\n", one_hot_result)

One-hot encoding:
 [[1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
